name: MixfryPlugin
version: '1.1.1'
main: com.mixfry.mixfryplugin.MixfryPlugin
api-version: '1.16'
commands:
  cookie_clicker:
    description: クッキークリッカーのメニューを開く
    aliases: [ cc ]
  cords:
    description: 現在の座標を表示する
  changelog:
    description: プラグインの変更点を表示します
  setting:
    description: セッティングメニューを開きます